### ISSUE TITLE
embedded-linux: broken link for BBB labs in the presentation

### ISSUE THREAD

**Issue by gmsotavio** [bootlin/training-materials#129]
Hello,

I was looking for the labs for BBB in the Embedded Linux training presentation but apparently the link is broken, as shown bellow.

https://github.com/bootlin/training-materials/blob/a97ebe4307585618ecadb0e5cec35d5e1f9cf8e2/slides/beagleboneblack-board-also-supported/beagleboneblack-board-also-supported.tex#L9

![image](https://user-images.githubusercontent.com/10669626/189686474-6890a9e4-4a52-4187-ad79-25178257658f.png)

**Comment by michaelopdenacker** [comment]
My fault here. The link was not supposed to exist.
We updated the materials to say that the instructions for the BBB board will be available by the end of the year (busy days!)
https://github.com/bootlin/training-materials/commit/028518318804dd7a69c22e432d9b4c667ad4ad9f
Thank you for reporting this issue!

**Comment by michaelopdenacker** [comment]
Oops, this issue is fixed as we now have instructions for the BBB and BBBW.
See https://bootlin.com/doc/training/embedded-linux/embedded-linux-slides.pdf#page=12
and https://bootlin.com/doc/training/embedded-linux-bbb/

Thanks
Michael.
