### ISSUE TITLE
Last slides: double / in the quiz and survey URLs

### ISSUE THREAD

**Issue by michaelopdenacker** [bootlin/training-materials#132]
In the below LaTeX code (in slides/last-slides/last-slides.tex):
\url{\sessionurl/survey.html}}

\sessionurl already contains a "/" character, causing to display a URL with a double "/" character.
Not incorrect, but this distracted a customer who reported this.

You can't remove the "/" in the above code without confusing LaTeX because it can't find the "\sessionurlsurvey" macro.

One solution could be to remove the trailing / in the SESSION_URL variable that is passed to our Makefile and is used to define \sessionurl, but it is likely to have side effects elsewhere.

I tried to use \sessionurl{}, but in the \url{} macro, the empty "{}" string appears in the output URL.
Any other way to address this minor issue?

**Comment by tpetazzoni** [comment]
I fixed this in https://github.com/bootlin/training-materials/commit/1b386a5697bd1569fd31a1c3c1984e9a34a1133f
