### ISSUE TITLE
embedded-linux: crosstool-ng 1.25 cannot download zlib 1.2.12

### ISSUE THREAD

**Issue by tpetazzoni** [bootlin/training-materials#137]
The zlib developers have moved/removed the 1.2.12 tarball of zlib, causing the crosstool-ng build to fail. This has been fixed in upstream crosstool-ng, but is not in a tagged release of Crosstool-NG.

Should we use a particular commit of Crosstool-NG ? Backport the fix ?

**Comment by michaelopdenacker** [comment]
I meant the one that works today :)

**Comment by lucaceresoli** [comment]
Done in https://github.com/bootlin/training-materials/commit/368cf91f1509fe0eace4c935795f51edaf6d91b0
