### ISSUE TITLE
debugging: remove -j flags in buildroot commands

### ISSUE THREAD

**Issue by Tropicao** [bootlin/training-materials#169]
Buildroot does not support by default parallel build at top level, except if BR2_PER_PACKAGE_DIRECTORIES is enabled (which still is experimental)

**Comment by Tropicao** [comment]
May not be relevant:
- `-j` is supported at top level make, as [stated by buildroot doc](https://buildroot.org/downloads/manual/manual.html), see 8.12
- even if said experimental, the support is under automatic test (see 2c41fb6225632ecea0b7008969bb70cf8e2636ef in buildroot)

**Comment by tpetazzoni** [comment]
Using -j at the top-level make in Buildroot has absolutely no effect, unless BR2_PER_PACKAGE_DIRECTORIES is enabled

**Comment by Tropicao** [comment]
Ah, thanks for the correction, I may have misread the doc (understood that one could either use `-j` OR enable `BR2_PER_PACKAGE_DIRECTORIES`, while both are in fact needed)
