### ISSUE TITLE
Invisible config option?

### ISSUE THREAD

**Issue by yjhn** [bootlin/training-materials#185]
At least in `qemu` configuration of `sysdev-kernel-cross-compiling`, the `CONFIG_GCC_PLUGINS` option is not visible in `make menuconfig`. Even though the variable is defined and can be found using `make menuconfig` built-in search, it does not show up under `General architecture-dependent options` (maybe because it `Depends on: HAVE_GCC_PLUGINS [=y] && CC_IS_GCC [=y] && n`?).
https://github.com/bootlin/training-materials/blob/f1716e35fb28336d5f0bb35cdf9c2a678adc6b54/labs/sysdev-kernel-cross-compiling/sysdev-kernel-cross-compiling.tex#L90-L92

P. S. also, in the same lab, it is incorrectly stated that Linux 5.9 is an LTS release.

**Comment by michaelopdenacker** [comment]
Hi Andrius
Thanks for reporting these issues!
They are fixed now:
https://github.com/bootlin/training-materials/commit/07c186ec2d4553025c6405bbe8f7bae6b98e852c
https://github.com/bootlin/training-materials/commit/1b60c1024bac1ad60f39085327a894bb00828773
Thanks again!
Cheers
Michael.
