### ISSUE TITLE
From Issue #129

### ISSUE THREAD

**Issue by silver2row** [bootlin/training-materials#188]
Hello,

I was wondering the same thing about issue #129 .

Are the bootlin people saying that since the beagleboard.org people have produced other boards, the BBB/BBBW slides have been put on hold?

I see the Buildroot slides still exist. This is nice. I am trying to see if the other slides will exist in the future or if plans have ceased to handle the builds around u-boot, the kernel, and busybox for the BBB/BBBW.

Seth

**Comment by michaelopdenacker** [comment]
No, we do have instructions on BBB and BBBW for the embedded Linux course, and we plan to support such boards in our courses for quite a long time, at least as long as they are available for purchase. At least, that's how plans are right now, but the decision is not up to me.
