### ISSUE TITLE
Yocto course: all agendas are for the online course

### ISSUE THREAD

**Issue by michaelopdenacker** [bootlin/training-materials#205]
For the Yocto course, because of the use of symbolic links, all agendas are online ones.
For example, the agendas don't mention the Ubuntu version which is supposed to be used.
See https://bootlin.com/doc/training/yocto/yocto-agenda.pdf

**Comment by lucaceresoli** [comment]
Fixed in https://github.com/bootlin/training-materials/commit/ddaa5987199853f2987aa9b666042f4295c3357e

**Comment by michaelopdenacker** [comment]
Great, many thanks.
I guess I didn't look properly when I saw symlinks.
