### ISSUE TITLE
[question] Can I use stm32mp157a_dk1_defconfig for STM32MP157D-DK1?

### ISSUE THREAD

**Issue by unicornx** [bootlin/training-materials#206]
Hi,  when I read "Preempt RT Training", it uses STM32MP157A as example and teaches us:
```
make stm32mp157a_dk1_defconfig
```
But I see according to "Understanding Linux real-time with PREEMPT_RT training" slides, "Supported hardware", it says:

> Discovery Kits from STMicroelectronics: STM32MP157A-DK1, STM32MP157D-DK1,
STM32MP157C-DK2 or STM32MP157F-DK2

I got a STM32MP157D-DK1, I think STM32MP157A-DK1 is too old.
So can I use `stm32mp157a_dk1_defconfig` for STM32MP157D-DK1? I checked the datasheet from STM and I believe STM32MP157D just has increased-frequency 800 MHz with same  CPU as STM32MP157A.

**Comment by michaelopdenacker** [comment]
Right, this always worked for me.
Thanks for asking!
