### ISSUE TITLE
Not Found for preempt-rt-labs.tar.xz

### ISSUE THREAD

**Issue by unicornx** [bootlin/training-materials#207]
[Preempt RT Training](https://bootlin.com/doc/training/preempt-rt/preempt-rt-labs.pdf)

section "Install lab data":

I think the lab data has been moved to https://github.com/bootlin/training-materials/tree/master/lab-data/preempt-rt, right?
But in the doc, it still tells us to `"wget https://bootlin.com/doc/training/preempt-rt/preempt-rt-labs.tar.xz"`, and this URL is invalid now.

**Comment by tpetazzoni** [comment]
Thanks a lot for the bug report, this is now fixed in our infrastructure!
