### ISSUE TITLE
BBB kernel configuration steps are unclear

### ISSUE THREAD

**Issue by Vishwajith-K** [bootlin/training-materials#36]
I am using BBB and Linux kernel and driver development training. Steps in the material are unclear on how to config the kernel for BBB board! Is `arch/arm/configs/omap2plus_defconfig` the file that needs to used as `.config`? OR is there any target in kernel's make to pick corresponding target for am335x boards?

**Comment by michaelopdenacker** [comment]
Hi
Thanks for reporting this.
I read our instructions again: "Configure your kernel sources with the ready-made configuration for boards in the OMAP2 and
later family which the AM335x found in the BeagleBone belongs to".
IMHO, this is explicit enough, given the explanations already given in the lectures.
If you expected to get instructions that you would run without understanding them, that's not how our materials. They push people to look for solutions by themselves. We just give a minimum of information to find the right level of difficulty. We believe it helps with learning.
Cheers
