### ISSUE TITLE
embedded-linux-labs add footnote description of UBI issue when using U-Boot + MMC

### ISSUE THREAD

**Issue by ztporter** [bootlin/training-materials#39]
First, thank you guys so much for putting together these embedded linux slides and labs and making them freely available. They have been a tremendous help in better understanding all the nuances of the embedded linux development ecosystem.

In the latest embedded-linux-lab.pdf (7/22/21) when talking about using UBIFS and UBI images on p. 28, you say:
> "Also remove the SD card, to resume to the former way of booting. *That’s important because
there is currently an issue with U-Boot compiled from the MMC configuration, which causes
UBI incompatibilities between U-Boot and Linux.*"

Would you please consider adding a footnote here to provide some additional information about this issue similar to footnote 13 in which you give an excellent description about needing to use the `trimffs` option with `nand write` to prevent running into ECC issues when writing the UBI images. My confusion with the existing information is whether or not this is a quirk of the particular hardware platform, a particular version of u-boot, or if this is a general issue with trying to pass a ubifs to linux when u-boot is using an environment located in mmc.

The first few times I tried to work through this section I glanced right over the line that mentioned removing the SD card and I kept getting strange ubi read errors related to bad ecc values when booting my kernel `ubi_io_read: error -74 (ECC error)`. I dug through the config and .dts files for both u-boot and the kernel looking for anything related to NAND, ECC, and/or UBI trying to diagnose the issue, but I was unable to locate the source of the problem.

**Comment by michaelopdenacker** [comment]
Hi Zach
Thank you for the feedback.
I cannot tell you more at this stage. I can just say that if you boot U-Boot from NAND with the version we're supporting and U-Boot's NAND flash configuration, it will work if you follow our instructions, in particular the ones for flashing U-Boot. I've been doing this some many times.
You may also try with the latest version of U-Boot.
Cheers
Michael.
