### ISSUE TITLE
Embedded Linux on SAMA5D3: stop using SAM-BA

### ISSUE THREAD

**Issue by michaelopdenacker** [bootlin/training-materials#73]
The use of SAM-BA is a significant source of problems for people doing labs remotely. This could be a learning opportunity, but this is only relevant in the context of Microchip boards.

Instead, I propose to instruct people to prepare an MMC/SD card and compile U-Boot for booting from MMC from the start. This is much more generic and we already do this in the STM32 and QEMU labs. If we want to keep the flash labs, we will still be able to flash U-Boot on NAND flash using U-Boot on MMC.

What do you think?

**Comment by tpetazzoni** [comment]
Not relevant, as we are going to move away from the Microchip board anyway.
