### ISSUE TITLE
kernel: Clarify use of the word module/driver/kerbnel/built-in

### ISSUE THREAD

**Issue by clementleger** [bootlin/training-materials#83]
Sometimes modules is used to designate a driver. Rework that to be coherent. A module is a loadable module and a driver car be compiled as a module or built-in

**Comment by miquelraynal** [comment]
I went through all the occurrences of the word "module" and I did not find a situation where it was misused. I'm closing the issue because if we encounter again the problem this is something that can be quickly fixed as it is not so spread across the materials.
