### ISSUE TITLE
kernel: remove cscope presentation

### ISSUE THREAD

**Issue by clementleger** [bootlin/training-materials#92]
This is something really specific on tooling and it does not add any valuable information.

**Comment by clementleger** [comment]
Hi @mattthias, 

We considered removing this section because it does not seems to be something that is used by a lot of people. Since even internally there is not a lot of cscope users, it makes sense to remove it. We need to rework that part some maybe it'll be removed soon.

**Comment by miquelraynal** [comment]
Actually I just reworked the entire section about IDEs, web browsers, Git... So Cscope is gone now.
