### ISSUE TITLE
yocto: SERIAL_CONSOLE is deprecated, use SERIAL_CONSOLES

### ISSUE THREAD

**Issue by lucaceresoli** [bootlin/training-materials#97]
`slides/yocto-bsp/yocto-bsp.tex` shows an example machine config that defines `SERIAL_CONSOLE`, which is deprecated and should be replaced with `SERIAL_CONSOLES`.

We should find another machine config that uses `SERIAL_CONSOLES` and is also simple and short enough to fit in a slide.

**Comment by alexandrebelloni** [comment]
Fixed in 3e2d382bba9da6cbd01dc1f7f44dd6de022c8352

**Comment by alexandrebelloni** [comment]
Fixed in 3e2d382bba9da6cbd01dc1f7f44dd6de022c8352
